# # 请在下方输入你的Python代码!
import turtle as t
t.penup()
t.goto(-45,0)
t.pendown()
t.pencolor("blue")
t.pensize(10)
t.circle(100)
t.penup()
t.goto(70,-100)
t.pendown()
t.pencolor("yellow")
t.circle(100)
t.penup()
t.goto(200,0)
t.pendown()
t.pencolor("black")
t.circle(100)
t.penup()
t.goto(300,-100)
t.pendown()
t.pencolor("green")
t.circle(100)
t.penup()
t.goto(430,0)
t.pendown()
t.pencolor("red")
t.circle(100)